### ISSUE TITLE
go-connections runs afoul of Go proverbs

### ISSUE THREAD

**Issue by stevvooe** [docker/go-connections#1]
"A little copying is better than a little dependency."

This package contains a large amount of boilerplate that should just become part of the target project, rather than used across projects.

Please see https://go-proverbs.github.io/ for a full list.

**Comment by calavera** [comment]
I agree. Please, feel free to not use it in your projects.

**Comment by stevvooe** [comment]
@calavera So, what is the point in having this project? Will docker use it?
