### ISSUE TITLE
v0.3.0 (or v0.2.1) release 👼

### ISSUE THREAD

**Issue by vdemeester** [docker/go-connections#16]
We should tag the v0.3.0 (or v0.2.1) release (and update vendoring in `docker/docker`)

/ping @calavera @thaJeztah @icecrime @dnephin

**Comment by thaJeztah** [comment]
Guess it depends on the changes; if only bug fixes, then 0.2.1, otherwise 0.3;
https://github.com/docker/go-connections/compare/v0.2.0...master

**Comment by dnephin** [comment]
`0.2.1` sounds appropriate, I think these are basically just bug fixes.

**Comment by thaJeztah** [comment]
SGTM

**Comment by vdemeester** [comment]
Ok good, I pushed a `v0.2.1` tag. I'll update `hack/vendor.sh` of `docker/docker` soon then 👼
