### ISSUE TITLE
cannot bump go-connections version in docker due to compilation error

### ISSUE THREAD

**Issue by adshmh** [docker/go-connections#32]
While trying to vendor go-connections in docker, as a follow up to #31, I get compilation errors. 

This is because of a change to 'NewUnixSocket', changing the type of group argument from string to int. 

https://github.com/docker/go-connections/blob/1b14b2d192e2f91cdc2bc6bf9aee0b0e116eed42/sockets/unix_socket.go#L11-L12

`// NewUnixSocket creates a unix socket with the specified path and group.
func NewUnixSocket(path string, gid int) (net.Listener, error) {
if err := syscall.Unlink(path); err != nil && !os.IsNotExist(err) {`

The NewUnixSocket interface now expects an integer as gid, instead of group name, which was the previous signature of 'NewUnixSocket'.

This breaks docker/docker, as the code depends on the version that accepted a string as group:

https://github.com/docker/docker/blob/40c51569e2a557e6656ea4314c824fb1eabb2c4e/pkg/listeners/listeners_unix.go#L34

`l, err := sockets.NewUnixSocket(addr, socketGroup)`

**Comment by adshmh** [comment]
Assuming I am not missing anything, how can this be fixed?

I can submit a PR to try to resolve the groupname on docker side if that is a good solution, but does that need to include the vendoring changes for NewUnixSocket too?

**Comment by adshmh** [comment]
ping @tiborvass, @cyli

**Comment by tiborvass** [comment]
https://github.com/docker/docker/pull/30729 will address your concerns.
