### ISSUE TITLE
sockets/unix_socket.go: os.Chown(path, 0, gid), why uid is hard-coded to 0?

### ISSUE THREAD

**Issue by duanbing** [docker/go-connections#54]
I  think if this is a separated repo, we can not make sure sock will be created under root role. So I propose changing 0 to os.Getuid(), or like gid assigned by custom

**Comment by duanbing** [comment]
@thaJeztah

**Comment by thaJeztah** [comment]
Yes, I think this originates from the fact that this code was moved out from the moby/moby repository. I wonder though if this would even work if the code was not executed as `root` (as non-root users won't have `CAP_CHOWN`, and won't be able to do the `chown`) 🤔

**Comment by duanbing** [comment]
Yes, you are right. A higher privilege is needed.  My change is a little trick, I just `chown` the sock file with the same user of itself's, so it run ok. But it seems better to remove the `Chown` logic.  How do you think of it？  @thaJeztah

**Comment by thaJeztah** [comment]
I suspect the Chown logic is used (for `dockerd`) so that the socket's group will be set `docker` (which is not the primary group for `root`). So effectively, this code _must_ be run as `root` (if chown is used); possibly it could take both a `uid` _and_ a `gid`, and only run the `Chmod` if those don't match the current user's uid/gid 🤔

**Comment by duanbing** [comment]
OK, I will create a PR later for this.

**Comment by duanbing** [comment]
@thaJeztah  I just set up the `uid` of `Chown` with a parameter uid.  the syscall `chown` will skip the real modification when uid/gid matches, as far as I know, it was implemented in MacOS,https://opensource.apple.com/source/file_cmds/file_cmds-90/chown/chown.c.auto.html, For Linux, I just went through some tests, it works well too.
