### ISSUE TITLE
sockets_unix.go:24:28: undefined: context

### ISSUE THREAD

**Issue by romantomchak** [docker/go-connections#60]
Hi,

After last update an issue appear during my application compilation:

`sockets_unix.go:24:28: undefined: context`

in sockets_unix.go you are using context.Context but context package is not imported.

usage:

```go
tr.DialContext = func(ctx context.Context, _, _ string) (net.Conn, error) {
    return dialer.DialContext(ctx, proto, addr)
}
```

import:

```go
import (
	"fmt"
	"net"
	"net/http"
	"syscall"
	"time"
)
```

**Comment by AkihiroSuda** [comment]
https://github.com/docker/go-connections/pull/58

cc @PaulSD

**Comment by PaulSD** [comment]
:man_facepalming:

Working on a fix.
