### ISSUE TITLE
Certificate used in tlsconfig/config_test.go expired

### ISSUE THREAD

**Issue by lucaskanashiro** [docker/go-connections#83]
According to this comment in the code:

https://github.com/docker/go-connections/blob/851a7fca8220be01ebba8dd39c1e40737a1858ac/tlsconfig/config_test.go#L14

The certificate expired Mar 17, 2021.  Due to that, `TestConfigServerExclusiveRootPools` and `TestConfigClientExclusiveRootPools` are failing. Take a look at this test log in the Ubuntu infrastructure:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/amd64/g/golang-github-docker-go-connections/20210319_032851_d71cb@/log.gz

**Comment by gotmax23** [comment]
@thaJeztah fixed this in https://github.com/docker/go-connections/commit/f454ee8e77fd2360bf8f49a76ab749c52eb58348, but then it expired again. Can you please fix it again?
